name: build-and-push

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cucurbita:${{ github.event.release.tag_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cucurbita:${{ 'latest' }}
      - name: build and publish dev
        if: github.event_name != 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cucurbita:${{ 'dev' }}
